; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27040.0 

	TITLE	G:\CtP2\zlib1211\zlib-1.2.11\compress.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	_compress
PUBLIC	_compress2
PUBLIC	_compressBound
EXTRN	_deflate:PROC
EXTRN	_deflateEnd:PROC
EXTRN	_deflateInit_:PROC
EXTRN	@_RTC_CheckStackVars@8:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
_DATA	SEGMENT
$SG4901	DB	'1.2.11', 00H
_DATA	ENDS
; Function compile flags: /Odtp /RTCsu
; File g:\ctp2\zlib1211\zlib-1.2.11\compress.c
_TEXT	SEGMENT
_sourceLen$ = 8						; size = 4
_compressBound PROC

; 83   : {

	push	ebp
	mov	ebp, esp

; 84   :     return sourceLen + (sourceLen >> 12) + (sourceLen >> 14) +

	mov	eax, DWORD PTR _sourceLen$[ebp]
	shr	eax, 12					; 0000000cH
	add	eax, DWORD PTR _sourceLen$[ebp]
	mov	ecx, DWORD PTR _sourceLen$[ebp]
	shr	ecx, 14					; 0000000eH
	add	eax, ecx
	mov	edx, DWORD PTR _sourceLen$[ebp]
	shr	edx, 25					; 00000019H
	lea	eax, DWORD PTR [eax+edx+13]

; 85   :            (sourceLen >> 25) + 13;
; 86   : }

	pop	ebp
	ret	0
_compressBound ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File g:\ctp2\zlib1211\zlib-1.2.11\compress.c
_TEXT	SEGMENT
tv86 = -92						; size = 4
tv80 = -88						; size = 4
tv76 = -84						; size = 4
tv72 = -80						; size = 4
_left$ = -76						; size = 4
_max$ = -72						; size = 4
_err$ = -68						; size = 4
_stream$ = -60						; size = 56
_dest$ = 8						; size = 4
_destLen$ = 12						; size = 4
_source$ = 16						; size = 4
_sourceLen$ = 20					; size = 4
_level$ = 24						; size = 4
_compress2 PROC

; 28   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 92					; 0000005cH
	push	edi
	lea	edi, DWORD PTR [ebp-92]
	mov	ecx, 23					; 00000017H
	mov	eax, -858993460				; ccccccccH
	rep stosd

; 29   :     z_stream stream;
; 30   :     int err;
; 31   :     const uInt max = (uInt)-1;

	mov	DWORD PTR _max$[ebp], -1

; 32   :     uLong left;
; 33   : 
; 34   :     left = *destLen;

	mov	eax, DWORD PTR _destLen$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _left$[ebp], ecx

; 35   :     *destLen = 0;

	mov	edx, DWORD PTR _destLen$[ebp]
	mov	DWORD PTR [edx], 0

; 36   : 
; 37   :     stream.zalloc = (alloc_func)0;

	mov	DWORD PTR _stream$[ebp+32], 0

; 38   :     stream.zfree = (free_func)0;

	mov	DWORD PTR _stream$[ebp+36], 0

; 39   :     stream.opaque = (voidpf)0;

	mov	DWORD PTR _stream$[ebp+40], 0

; 40   : 
; 41   :     err = deflateInit(&stream, level);

	push	56					; 00000038H
	push	OFFSET $SG4901
	mov	eax, DWORD PTR _level$[ebp]
	push	eax
	lea	ecx, DWORD PTR _stream$[ebp]
	push	ecx
	call	_deflateInit_
	add	esp, 16					; 00000010H
	mov	DWORD PTR _err$[ebp], eax

; 42   :     if (err != Z_OK) return err;

	cmp	DWORD PTR _err$[ebp], 0
	je	SHORT $LN5@compress2
	mov	eax, DWORD PTR _err$[ebp]
	jmp	$LN1@compress2
$LN5@compress2:

; 43   : 
; 44   :     stream.next_out = dest;

	mov	edx, DWORD PTR _dest$[ebp]
	mov	DWORD PTR _stream$[ebp+12], edx

; 45   :     stream.avail_out = 0;

	mov	DWORD PTR _stream$[ebp+16], 0

; 46   :     stream.next_in = (z_const Bytef *)source;

	mov	eax, DWORD PTR _source$[ebp]
	mov	DWORD PTR _stream$[ebp], eax

; 47   :     stream.avail_in = 0;

	mov	DWORD PTR _stream$[ebp+4], 0
$LN4@compress2:

; 48   : 
; 49   :     do {
; 50   :         if (stream.avail_out == 0) {

	cmp	DWORD PTR _stream$[ebp+16], 0
	jne	SHORT $LN6@compress2

; 51   :             stream.avail_out = left > (uLong)max ? max : (uInt)left;

	mov	ecx, DWORD PTR _left$[ebp]
	cmp	ecx, DWORD PTR _max$[ebp]
	jbe	SHORT $LN9@compress2
	mov	edx, DWORD PTR _max$[ebp]
	mov	DWORD PTR tv72[ebp], edx
	jmp	SHORT $LN10@compress2
$LN9@compress2:
	mov	eax, DWORD PTR _left$[ebp]
	mov	DWORD PTR tv72[ebp], eax
$LN10@compress2:
	mov	ecx, DWORD PTR tv72[ebp]
	mov	DWORD PTR _stream$[ebp+16], ecx

; 52   :             left -= stream.avail_out;

	mov	edx, DWORD PTR _left$[ebp]
	sub	edx, DWORD PTR _stream$[ebp+16]
	mov	DWORD PTR _left$[ebp], edx
$LN6@compress2:

; 53   :         }
; 54   :         if (stream.avail_in == 0) {

	cmp	DWORD PTR _stream$[ebp+4], 0
	jne	SHORT $LN7@compress2

; 55   :             stream.avail_in = sourceLen > (uLong)max ? max : (uInt)sourceLen;

	mov	eax, DWORD PTR _sourceLen$[ebp]
	cmp	eax, DWORD PTR _max$[ebp]
	jbe	SHORT $LN11@compress2
	mov	ecx, DWORD PTR _max$[ebp]
	mov	DWORD PTR tv76[ebp], ecx
	jmp	SHORT $LN12@compress2
$LN11@compress2:
	mov	edx, DWORD PTR _sourceLen$[ebp]
	mov	DWORD PTR tv76[ebp], edx
$LN12@compress2:
	mov	eax, DWORD PTR tv76[ebp]
	mov	DWORD PTR _stream$[ebp+4], eax

; 56   :             sourceLen -= stream.avail_in;

	mov	ecx, DWORD PTR _sourceLen$[ebp]
	sub	ecx, DWORD PTR _stream$[ebp+4]
	mov	DWORD PTR _sourceLen$[ebp], ecx
$LN7@compress2:

; 57   :         }
; 58   :         err = deflate(&stream, sourceLen ? Z_NO_FLUSH : Z_FINISH);

	cmp	DWORD PTR _sourceLen$[ebp], 0
	je	SHORT $LN13@compress2
	mov	DWORD PTR tv80[ebp], 0
	jmp	SHORT $LN14@compress2
$LN13@compress2:
	mov	DWORD PTR tv80[ebp], 4
$LN14@compress2:
	mov	edx, DWORD PTR tv80[ebp]
	push	edx
	lea	eax, DWORD PTR _stream$[ebp]
	push	eax
	call	_deflate
	add	esp, 8
	mov	DWORD PTR _err$[ebp], eax

; 59   :     } while (err == Z_OK);

	cmp	DWORD PTR _err$[ebp], 0
	je	$LN4@compress2

; 60   : 
; 61   :     *destLen = stream.total_out;

	mov	ecx, DWORD PTR _destLen$[ebp]
	mov	edx, DWORD PTR _stream$[ebp+20]
	mov	DWORD PTR [ecx], edx

; 62   :     deflateEnd(&stream);

	lea	eax, DWORD PTR _stream$[ebp]
	push	eax
	call	_deflateEnd
	add	esp, 4

; 63   :     return err == Z_STREAM_END ? Z_OK : err;

	cmp	DWORD PTR _err$[ebp], 1
	jne	SHORT $LN15@compress2
	mov	DWORD PTR tv86[ebp], 0
	jmp	SHORT $LN16@compress2
$LN15@compress2:
	mov	ecx, DWORD PTR _err$[ebp]
	mov	DWORD PTR tv86[ebp], ecx
$LN16@compress2:
	mov	eax, DWORD PTR tv86[ebp]
$LN1@compress2:

; 64   : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN19@compress2
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	add	esp, 92					; 0000005cH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	2
$LN19@compress2:
	DD	1
	DD	$LN18@compress2
$LN18@compress2:
	DD	-60					; ffffffc4H
	DD	56					; 00000038H
	DD	$LN17@compress2
$LN17@compress2:
	DB	115					; 00000073H
	DB	116					; 00000074H
	DB	114					; 00000072H
	DB	101					; 00000065H
	DB	97					; 00000061H
	DB	109					; 0000006dH
	DB	0
_compress2 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File g:\ctp2\zlib1211\zlib-1.2.11\compress.c
_TEXT	SEGMENT
_dest$ = 8						; size = 4
_destLen$ = 12						; size = 4
_source$ = 16						; size = 4
_sourceLen$ = 20					; size = 4
_compress PROC

; 73   : {

	push	ebp
	mov	ebp, esp

; 74   :     return compress2(dest, destLen, source, sourceLen, Z_DEFAULT_COMPRESSION);

	push	-1
	mov	eax, DWORD PTR _sourceLen$[ebp]
	push	eax
	mov	ecx, DWORD PTR _source$[ebp]
	push	ecx
	mov	edx, DWORD PTR _destLen$[ebp]
	push	edx
	mov	eax, DWORD PTR _dest$[ebp]
	push	eax
	call	_compress2
	add	esp, 20					; 00000014H

; 75   : }

	cmp	ebp, esp
	call	__RTC_CheckEsp
	pop	ebp
	ret	0
_compress ENDP
_TEXT	ENDS
END
