; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27040.0 

	TITLE	G:\CtP2\zlib1211\zlib-1.2.11\contrib\testzlib\testzlib.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	___local_stdio_printf_options
PUBLIC	__vfprintf_l
PUBLIC	_printf
PUBLIC	_Int64ShrlMod32@12
PUBLIC	_MyDoMinus64
PUBLIC	_myGetRDTSC32
PUBLIC	_BeginCountRdtsc
PUBLIC	_GetResRdtsc
PUBLIC	_BeginCountPerfCounter
PUBLIC	_GetMsecSincePerfCounter
PUBLIC	_ReadFileMemory
PUBLIC	_main
PUBLIC	__real@408f400000000000
PUBLIC	__xmm@41f00000000000000000000000000000
EXTRN	__imp____acrt_iob_func:PROC
EXTRN	__imp__fclose:PROC
EXTRN	__imp__fopen:PROC
EXTRN	__imp__fread:PROC
EXTRN	__imp__fseek:PROC
EXTRN	__imp__ftell:PROC
EXTRN	__imp____stdio_common_vfprintf:PROC
EXTRN	__imp__malloc:PROC
EXTRN	__imp__realloc:PROC
EXTRN	__imp__atol:PROC
EXTRN	_memcmp:PROC
EXTRN	_memset:PROC
EXTRN	__imp__QueryPerformanceCounter@4:PROC
EXTRN	__imp__QueryPerformanceFrequency@4:PROC
EXTRN	__imp__GetTickCount@0:PROC
EXTRN	_deflate:PROC
EXTRN	_deflateEnd:PROC
EXTRN	_inflate:PROC
EXTRN	_inflateEnd:PROC
EXTRN	_deflateInit_:PROC
EXTRN	_inflateInit_:PROC
EXTRN	@_RTC_CheckStackVars@8:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__fltused:DWORD
_DATA	SEGMENT
COMM	?_OptionsStorage@?1??__local_stdio_printf_options@@9@9:QWORD							; `__local_stdio_printf_options'::`2'::_OptionsStorage
_DATA	ENDS
;	COMDAT __xmm@41f00000000000000000000000000000
CONST	SEGMENT
__xmm@41f00000000000000000000000000000 DB 00H, 00H, 00H, 00H, 00H, 00H, 00H
	DB	00H, 00H, 00H, 00H, 00H, 00H, 00H, 0f0H, 'A'
CONST	ENDS
;	COMDAT __real@408f400000000000
CONST	SEGMENT
__real@408f400000000000 DQ 0408f400000000000r	; 1000
CONST	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
_DATA	SEGMENT
$SG96905 DB	'rb', 00H
	ORG $+5
$SG96966 DB	'run TestZlib <File> [BlockSizeCompress] [BlockSizeUncomp'
	DB	'ress] [compres. level]', 0aH, 00H
$SG96969 DB	'error reading %s', 0aH, 00H
	ORG $+2
$SG96970 DB	'file %s read, %u bytes', 0aH, 00H
$SG96974 DB	'1.2.11', 00H
	ORG $+1
$SG96975 DB	'total compress size = %u, in %u step', 0aH, 00H
	ORG $+2
$SG96976 DB	'time = %u msec = %f sec', 0aH, 00H
	ORG $+3
$SG96977 DB	'defcpr time QP = %u msec = %f sec', 0aH, 00H
	ORG $+1
$SG96978 DB	'defcpr result rdtsc = %I64x', 0aH, 0aH, 00H
	ORG $+2
$SG96979 DB	'1.2.11', 00H
	ORG $+1
$SG96980 DB	'total uncompress size = %u, in %u step', 0aH, 00H
$SG96981 DB	'time = %u msec = %f sec', 0aH, 00H
	ORG $+3
$SG96982 DB	'uncpr  time QP = %u msec = %f sec', 0aH, 00H
	ORG $+1
$SG96983 DB	'uncpr  result rdtsc = %I64x', 0aH, 0aH, 00H
	ORG $+2
$SG96986 DB	'compare ok', 0aH, 00H
_DATA	ENDS
; Function compile flags: /Odtp /RTCsu
; File g:\ctp2\zlib1211\zlib-1.2.11\contrib\testzlib\testzlib.c
_TEXT	SEGMENT
tv450 = -316						; size = 4
tv443 = -312						; size = 4
tv241 = -308						; size = 4
tv380 = -304						; size = 4
tv373 = -300						; size = 4
tv153 = -296						; size = 4
tv150 = -292						; size = 4
_all_read_before$1 = -288				; size = 4
_step$2 = -284						; size = 4
_lOrigDone$3 = -280					; size = 4
_lOrigToDo$4 = -276					; size = 4
_ret$5 = -272						; size = 4
_zcpr$6 = -264						; size = 56
_all_read_before$7 = -204				; size = 4
_step$8 = -200						; size = 4
_lOrigDone$9 = -196					; size = 4
_lOrigToDo$10 = -192					; size = 4
_ret$11 = -188						; size = 4
_zcpr$12 = -180						; size = 56
_dwResRdtsc$ = -116					; size = 8
_li_rdtsc$ = -100					; size = 8
_li_qp$ = -84						; size = 8
_dwMsecQP$ = -72					; size = 4
_dwGetTick$ = -68					; size = 4
_lSizeUncpr$ = -64					; size = 4
_lSizeCpr$ = -60					; size = 4
_UncprPtr$ = -56					; size = 4
_CprPtr$ = -52						; size = 4
_lCompressedSize$ = -48					; size = 4
_lBufferSizeUncpr$ = -44				; size = 4
_lBufferSizeCpr$ = -40					; size = 4
_FilePtr$ = -32						; size = 4
_lFileSize$ = -20					; size = 4
_cprLevel$ = -12					; size = 4
_BlockSizeUncompress$ = -8				; size = 4
_BlockSizeCompress$ = -4				; size = 4
_argc$ = 8						; size = 4
_argv$ = 12						; size = 4
_main	PROC

; 146  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 316				; 0000013cH
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-316]
	mov	ecx, 79					; 0000004fH
	mov	eax, -858993460				; ccccccccH
	rep stosd

; 147  :     int BlockSizeCompress=0x8000;

	mov	DWORD PTR _BlockSizeCompress$[ebp], 32768 ; 00008000H

; 148  :     int BlockSizeUncompress=0x8000;

	mov	DWORD PTR _BlockSizeUncompress$[ebp], 32768 ; 00008000H

; 149  :     int cprLevel=Z_DEFAULT_COMPRESSION ;

	mov	DWORD PTR _cprLevel$[ebp], -1

; 150  :     long lFileSize;
; 151  :     unsigned char* FilePtr;
; 152  :     long lBufferSizeCpr;
; 153  :     long lBufferSizeUncpr;
; 154  :     long lCompressedSize=0;

	mov	DWORD PTR _lCompressedSize$[ebp], 0

; 155  :     unsigned char* CprPtr;
; 156  :     unsigned char* UncprPtr;
; 157  :     long lSizeCpr,lSizeUncpr;
; 158  :     DWORD dwGetTick,dwMsecQP;
; 159  :     LARGE_INTEGER li_qp,li_rdtsc,dwResRdtsc;
; 160  : 
; 161  :     if (argc<=1)

	cmp	DWORD PTR _argc$[ebp], 1
	jg	SHORT $LN8@main

; 162  :     {
; 163  :         printf("run TestZlib <File> [BlockSizeCompress] [BlockSizeUncompress] [compres. level]\n");

	push	OFFSET $SG96966
	call	_printf
	add	esp, 4

; 164  :         return 0;

	xor	eax, eax
	jmp	$LN1@main
$LN8@main:

; 165  :     }
; 166  : 
; 167  :     if (ReadFileMemory(argv[1],&lFileSize,&FilePtr)==0)

	lea	eax, DWORD PTR _FilePtr$[ebp]
	push	eax
	lea	ecx, DWORD PTR _lFileSize$[ebp]
	push	ecx
	mov	edx, 4
	shl	edx, 0
	mov	eax, DWORD PTR _argv$[ebp]
	mov	ecx, DWORD PTR [eax+edx]
	push	ecx
	call	_ReadFileMemory
	add	esp, 12					; 0000000cH
	test	eax, eax
	jne	SHORT $LN9@main

; 168  :     {
; 169  :         printf("error reading %s\n",argv[1]);

	mov	edx, 4
	shl	edx, 0
	mov	eax, DWORD PTR _argv$[ebp]
	mov	ecx, DWORD PTR [eax+edx]
	push	ecx
	push	OFFSET $SG96969
	call	_printf
	add	esp, 8

; 170  :         return 1;

	mov	eax, 1
	jmp	$LN1@main

; 171  :     }

	jmp	SHORT $LN10@main
$LN9@main:

; 172  :     else printf("file %s read, %u bytes\n",argv[1],lFileSize);

	mov	edx, DWORD PTR _lFileSize$[ebp]
	push	edx
	mov	eax, 4
	shl	eax, 0
	mov	ecx, DWORD PTR _argv$[ebp]
	mov	edx, DWORD PTR [ecx+eax]
	push	edx
	push	OFFSET $SG96970
	call	_printf
	add	esp, 12					; 0000000cH
$LN10@main:

; 173  : 
; 174  :     if (argc>=3)

	cmp	DWORD PTR _argc$[ebp], 3
	jl	SHORT $LN11@main

; 175  :         BlockSizeCompress=atol(argv[2]);

	mov	eax, 4
	shl	eax, 1
	mov	esi, esp
	mov	ecx, DWORD PTR _argv$[ebp]
	mov	edx, DWORD PTR [ecx+eax]
	push	edx
	call	DWORD PTR __imp__atol
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _BlockSizeCompress$[ebp], eax
$LN11@main:

; 176  : 
; 177  :     if (argc>=4)

	cmp	DWORD PTR _argc$[ebp], 4
	jl	SHORT $LN12@main

; 178  :         BlockSizeUncompress=atol(argv[3]);

	mov	eax, 4
	imul	ecx, eax, 3
	mov	esi, esp
	mov	edx, DWORD PTR _argv$[ebp]
	mov	eax, DWORD PTR [edx+ecx]
	push	eax
	call	DWORD PTR __imp__atol
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _BlockSizeUncompress$[ebp], eax
$LN12@main:

; 179  : 
; 180  :     if (argc>=5)

	cmp	DWORD PTR _argc$[ebp], 5
	jl	SHORT $LN13@main

; 181  :         cprLevel=(int)atol(argv[4]);

	mov	ecx, 4
	shl	ecx, 2
	mov	esi, esp
	mov	edx, DWORD PTR _argv$[ebp]
	mov	eax, DWORD PTR [edx+ecx]
	push	eax
	call	DWORD PTR __imp__atol
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _cprLevel$[ebp], eax
$LN13@main:

; 182  : 
; 183  :     lBufferSizeCpr = lFileSize + (lFileSize/0x10) + 0x200;

	mov	eax, DWORD PTR _lFileSize$[ebp]
	cdq
	and	edx, 15					; 0000000fH
	add	eax, edx
	sar	eax, 4
	mov	ecx, DWORD PTR _lFileSize$[ebp]
	lea	edx, DWORD PTR [ecx+eax+512]
	mov	DWORD PTR _lBufferSizeCpr$[ebp], edx

; 184  :     lBufferSizeUncpr = lBufferSizeCpr;

	mov	eax, DWORD PTR _lBufferSizeCpr$[ebp]
	mov	DWORD PTR _lBufferSizeUncpr$[ebp], eax

; 185  : 
; 186  :     CprPtr=(unsigned char*)malloc(lBufferSizeCpr + BlockSizeCompress);

	mov	ecx, DWORD PTR _lBufferSizeCpr$[ebp]
	add	ecx, DWORD PTR _BlockSizeCompress$[ebp]
	mov	esi, esp
	push	ecx
	call	DWORD PTR __imp__malloc
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _CprPtr$[ebp], eax

; 187  : 
; 188  :     BeginCountPerfCounter(&li_qp,TRUE);

	push	1
	lea	edx, DWORD PTR _li_qp$[ebp]
	push	edx
	call	_BeginCountPerfCounter
	add	esp, 8

; 189  :     dwGetTick=GetTickCount();

	mov	esi, esp
	call	DWORD PTR __imp__GetTickCount@0
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _dwGetTick$[ebp], eax

; 190  :     BeginCountRdtsc(&li_rdtsc);

	lea	eax, DWORD PTR _li_rdtsc$[ebp]
	push	eax
	call	_BeginCountRdtsc
	add	esp, 4

; 191  :     {
; 192  :         z_stream zcpr;
; 193  :         int ret=Z_OK;

	mov	DWORD PTR _ret$11[ebp], 0

; 194  :         long lOrigToDo = lFileSize;

	mov	ecx, DWORD PTR _lFileSize$[ebp]
	mov	DWORD PTR _lOrigToDo$10[ebp], ecx

; 195  :         long lOrigDone = 0;

	mov	DWORD PTR _lOrigDone$9[ebp], 0

; 196  :         int step=0;

	mov	DWORD PTR _step$8[ebp], 0

; 197  :         memset(&zcpr,0,sizeof(z_stream));

	push	56					; 00000038H
	push	0
	lea	edx, DWORD PTR _zcpr$12[ebp]
	push	edx
	call	_memset
	add	esp, 12					; 0000000cH

; 198  :         deflateInit(&zcpr,cprLevel);

	push	56					; 00000038H
	push	OFFSET $SG96974
	mov	eax, DWORD PTR _cprLevel$[ebp]
	push	eax
	lea	ecx, DWORD PTR _zcpr$12[ebp]
	push	ecx
	call	_deflateInit_
	add	esp, 16					; 00000010H

; 199  : 
; 200  :         zcpr.next_in = FilePtr;

	mov	edx, DWORD PTR _FilePtr$[ebp]
	mov	DWORD PTR _zcpr$12[ebp], edx

; 201  :         zcpr.next_out = CprPtr;

	mov	eax, DWORD PTR _CprPtr$[ebp]
	mov	DWORD PTR _zcpr$12[ebp+12], eax
$LN4@main:

; 202  : 
; 203  : 
; 204  :         do
; 205  :         {
; 206  :             long all_read_before = zcpr.total_in;

	mov	ecx, DWORD PTR _zcpr$12[ebp+8]
	mov	DWORD PTR _all_read_before$7[ebp], ecx

; 207  :             zcpr.avail_in = min(lOrigToDo,BlockSizeCompress);

	mov	edx, DWORD PTR _lOrigToDo$10[ebp]
	cmp	edx, DWORD PTR _BlockSizeCompress$[ebp]
	jge	SHORT $LN17@main
	mov	eax, DWORD PTR _lOrigToDo$10[ebp]
	mov	DWORD PTR tv150[ebp], eax
	jmp	SHORT $LN18@main
$LN17@main:
	mov	ecx, DWORD PTR _BlockSizeCompress$[ebp]
	mov	DWORD PTR tv150[ebp], ecx
$LN18@main:
	mov	edx, DWORD PTR tv150[ebp]
	mov	DWORD PTR _zcpr$12[ebp+4], edx

; 208  :             zcpr.avail_out = BlockSizeCompress;

	mov	eax, DWORD PTR _BlockSizeCompress$[ebp]
	mov	DWORD PTR _zcpr$12[ebp+16], eax

; 209  :             ret=deflate(&zcpr,(zcpr.avail_in==lOrigToDo) ? Z_FINISH : Z_SYNC_FLUSH);

	mov	ecx, DWORD PTR _zcpr$12[ebp+4]
	cmp	ecx, DWORD PTR _lOrigToDo$10[ebp]
	jne	SHORT $LN19@main
	mov	DWORD PTR tv153[ebp], 4
	jmp	SHORT $LN20@main
$LN19@main:
	mov	DWORD PTR tv153[ebp], 2
$LN20@main:
	mov	edx, DWORD PTR tv153[ebp]
	push	edx
	lea	eax, DWORD PTR _zcpr$12[ebp]
	push	eax
	call	_deflate
	add	esp, 8
	mov	DWORD PTR _ret$11[ebp], eax

; 210  :             lOrigDone += (zcpr.total_in-all_read_before);

	mov	ecx, DWORD PTR _zcpr$12[ebp+8]
	sub	ecx, DWORD PTR _all_read_before$7[ebp]
	add	ecx, DWORD PTR _lOrigDone$9[ebp]
	mov	DWORD PTR _lOrigDone$9[ebp], ecx

; 211  :             lOrigToDo -= (zcpr.total_in-all_read_before);

	mov	edx, DWORD PTR _zcpr$12[ebp+8]
	sub	edx, DWORD PTR _all_read_before$7[ebp]
	mov	eax, DWORD PTR _lOrigToDo$10[ebp]
	sub	eax, edx
	mov	DWORD PTR _lOrigToDo$10[ebp], eax

; 212  :             step++;

	mov	ecx, DWORD PTR _step$8[ebp]
	add	ecx, 1
	mov	DWORD PTR _step$8[ebp], ecx

; 213  :         } while (ret==Z_OK);

	cmp	DWORD PTR _ret$11[ebp], 0
	je	$LN4@main

; 214  : 
; 215  :         lSizeCpr=zcpr.total_out;

	mov	edx, DWORD PTR _zcpr$12[ebp+20]
	mov	DWORD PTR _lSizeCpr$[ebp], edx

; 216  :         deflateEnd(&zcpr);

	lea	eax, DWORD PTR _zcpr$12[ebp]
	push	eax
	call	_deflateEnd
	add	esp, 4

; 217  :         dwGetTick=GetTickCount()-dwGetTick;

	mov	esi, esp
	call	DWORD PTR __imp__GetTickCount@0
	cmp	esi, esp
	call	__RTC_CheckEsp
	sub	eax, DWORD PTR _dwGetTick$[ebp]
	mov	DWORD PTR _dwGetTick$[ebp], eax

; 218  :         dwMsecQP=GetMsecSincePerfCounter(li_qp,TRUE);

	push	1
	mov	ecx, DWORD PTR _li_qp$[ebp+4]
	push	ecx
	mov	edx, DWORD PTR _li_qp$[ebp]
	push	edx
	call	_GetMsecSincePerfCounter
	add	esp, 12					; 0000000cH
	mov	DWORD PTR _dwMsecQP$[ebp], eax

; 219  :         dwResRdtsc=GetResRdtsc(li_rdtsc,TRUE);

	push	1
	mov	eax, DWORD PTR _li_rdtsc$[ebp+4]
	push	eax
	mov	ecx, DWORD PTR _li_rdtsc$[ebp]
	push	ecx
	call	_GetResRdtsc
	add	esp, 12					; 0000000cH
	mov	DWORD PTR _dwResRdtsc$[ebp], eax
	mov	DWORD PTR _dwResRdtsc$[ebp+4], edx

; 220  :         printf("total compress size = %u, in %u step\n",lSizeCpr,step);

	mov	edx, DWORD PTR _step$8[ebp]
	push	edx
	mov	eax, DWORD PTR _lSizeCpr$[ebp]
	push	eax
	push	OFFSET $SG96975
	call	_printf
	add	esp, 12					; 0000000cH

; 221  :         printf("time = %u msec = %f sec\n",dwGetTick,dwGetTick/(double)1000.);

	mov	ecx, DWORD PTR _dwGetTick$[ebp]
	mov	DWORD PTR tv373[ebp], ecx
	cvtsi2sd xmm0, DWORD PTR tv373[ebp]
	mov	edx, DWORD PTR tv373[ebp]
	shr	edx, 31					; 0000001fH
	addsd	xmm0, QWORD PTR __xmm@41f00000000000000000000000000000[edx*8]
	divsd	xmm0, QWORD PTR __real@408f400000000000
	sub	esp, 8
	movsd	QWORD PTR [esp], xmm0
	mov	eax, DWORD PTR _dwGetTick$[ebp]
	push	eax
	push	OFFSET $SG96976
	call	_printf
	add	esp, 16					; 00000010H

; 222  :         printf("defcpr time QP = %u msec = %f sec\n",dwMsecQP,dwMsecQP/(double)1000.);

	mov	ecx, DWORD PTR _dwMsecQP$[ebp]
	mov	DWORD PTR tv380[ebp], ecx
	cvtsi2sd xmm0, DWORD PTR tv380[ebp]
	mov	edx, DWORD PTR tv380[ebp]
	shr	edx, 31					; 0000001fH
	addsd	xmm0, QWORD PTR __xmm@41f00000000000000000000000000000[edx*8]
	divsd	xmm0, QWORD PTR __real@408f400000000000
	sub	esp, 8
	movsd	QWORD PTR [esp], xmm0
	mov	eax, DWORD PTR _dwMsecQP$[ebp]
	push	eax
	push	OFFSET $SG96977
	call	_printf
	add	esp, 16					; 00000010H

; 223  :         printf("defcpr result rdtsc = %I64x\n\n",dwResRdtsc.QuadPart);

	mov	ecx, DWORD PTR _dwResRdtsc$[ebp+4]
	push	ecx
	mov	edx, DWORD PTR _dwResRdtsc$[ebp]
	push	edx
	push	OFFSET $SG96978
	call	_printf
	add	esp, 12					; 0000000cH

; 224  :     }
; 225  : 
; 226  :     CprPtr=(unsigned char*)realloc(CprPtr,lSizeCpr);

	mov	esi, esp
	mov	eax, DWORD PTR _lSizeCpr$[ebp]
	push	eax
	mov	ecx, DWORD PTR _CprPtr$[ebp]
	push	ecx
	call	DWORD PTR __imp__realloc
	add	esp, 8
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _CprPtr$[ebp], eax

; 227  :     UncprPtr=(unsigned char*)malloc(lBufferSizeUncpr + BlockSizeUncompress);

	mov	edx, DWORD PTR _lBufferSizeUncpr$[ebp]
	add	edx, DWORD PTR _BlockSizeUncompress$[ebp]
	mov	esi, esp
	push	edx
	call	DWORD PTR __imp__malloc
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _UncprPtr$[ebp], eax

; 228  : 
; 229  :     BeginCountPerfCounter(&li_qp,TRUE);

	push	1
	lea	eax, DWORD PTR _li_qp$[ebp]
	push	eax
	call	_BeginCountPerfCounter
	add	esp, 8

; 230  :     dwGetTick=GetTickCount();

	mov	esi, esp
	call	DWORD PTR __imp__GetTickCount@0
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _dwGetTick$[ebp], eax

; 231  :     BeginCountRdtsc(&li_rdtsc);

	lea	ecx, DWORD PTR _li_rdtsc$[ebp]
	push	ecx
	call	_BeginCountRdtsc
	add	esp, 4

; 232  :     {
; 233  :         z_stream zcpr;
; 234  :         int ret=Z_OK;

	mov	DWORD PTR _ret$5[ebp], 0

; 235  :         long lOrigToDo = lSizeCpr;

	mov	edx, DWORD PTR _lSizeCpr$[ebp]
	mov	DWORD PTR _lOrigToDo$4[ebp], edx

; 236  :         long lOrigDone = 0;

	mov	DWORD PTR _lOrigDone$3[ebp], 0

; 237  :         int step=0;

	mov	DWORD PTR _step$2[ebp], 0

; 238  :         memset(&zcpr,0,sizeof(z_stream));

	push	56					; 00000038H
	push	0
	lea	eax, DWORD PTR _zcpr$6[ebp]
	push	eax
	call	_memset
	add	esp, 12					; 0000000cH

; 239  :         inflateInit(&zcpr);

	push	56					; 00000038H
	push	OFFSET $SG96979
	lea	ecx, DWORD PTR _zcpr$6[ebp]
	push	ecx
	call	_inflateInit_
	add	esp, 12					; 0000000cH

; 240  : 
; 241  :         zcpr.next_in = CprPtr;

	mov	edx, DWORD PTR _CprPtr$[ebp]
	mov	DWORD PTR _zcpr$6[ebp], edx

; 242  :         zcpr.next_out = UncprPtr;

	mov	eax, DWORD PTR _UncprPtr$[ebp]
	mov	DWORD PTR _zcpr$6[ebp+12], eax
$LN7@main:

; 243  : 
; 244  : 
; 245  :         do
; 246  :         {
; 247  :             long all_read_before = zcpr.total_in;

	mov	ecx, DWORD PTR _zcpr$6[ebp+8]
	mov	DWORD PTR _all_read_before$1[ebp], ecx

; 248  :             zcpr.avail_in = min(lOrigToDo,BlockSizeUncompress);

	mov	edx, DWORD PTR _lOrigToDo$4[ebp]
	cmp	edx, DWORD PTR _BlockSizeUncompress$[ebp]
	jge	SHORT $LN21@main
	mov	eax, DWORD PTR _lOrigToDo$4[ebp]
	mov	DWORD PTR tv241[ebp], eax
	jmp	SHORT $LN22@main
$LN21@main:
	mov	ecx, DWORD PTR _BlockSizeUncompress$[ebp]
	mov	DWORD PTR tv241[ebp], ecx
$LN22@main:
	mov	edx, DWORD PTR tv241[ebp]
	mov	DWORD PTR _zcpr$6[ebp+4], edx

; 249  :             zcpr.avail_out = BlockSizeUncompress;

	mov	eax, DWORD PTR _BlockSizeUncompress$[ebp]
	mov	DWORD PTR _zcpr$6[ebp+16], eax

; 250  :             ret=inflate(&zcpr,Z_SYNC_FLUSH);

	push	2
	lea	ecx, DWORD PTR _zcpr$6[ebp]
	push	ecx
	call	_inflate
	add	esp, 8
	mov	DWORD PTR _ret$5[ebp], eax

; 251  :             lOrigDone += (zcpr.total_in-all_read_before);

	mov	edx, DWORD PTR _zcpr$6[ebp+8]
	sub	edx, DWORD PTR _all_read_before$1[ebp]
	add	edx, DWORD PTR _lOrigDone$3[ebp]
	mov	DWORD PTR _lOrigDone$3[ebp], edx

; 252  :             lOrigToDo -= (zcpr.total_in-all_read_before);

	mov	eax, DWORD PTR _zcpr$6[ebp+8]
	sub	eax, DWORD PTR _all_read_before$1[ebp]
	mov	ecx, DWORD PTR _lOrigToDo$4[ebp]
	sub	ecx, eax
	mov	DWORD PTR _lOrigToDo$4[ebp], ecx

; 253  :             step++;

	mov	edx, DWORD PTR _step$2[ebp]
	add	edx, 1
	mov	DWORD PTR _step$2[ebp], edx

; 254  :         } while (ret==Z_OK);

	cmp	DWORD PTR _ret$5[ebp], 0
	je	$LN7@main

; 255  : 
; 256  :         lSizeUncpr=zcpr.total_out;

	mov	eax, DWORD PTR _zcpr$6[ebp+20]
	mov	DWORD PTR _lSizeUncpr$[ebp], eax

; 257  :         inflateEnd(&zcpr);

	lea	ecx, DWORD PTR _zcpr$6[ebp]
	push	ecx
	call	_inflateEnd
	add	esp, 4

; 258  :         dwGetTick=GetTickCount()-dwGetTick;

	mov	esi, esp
	call	DWORD PTR __imp__GetTickCount@0
	cmp	esi, esp
	call	__RTC_CheckEsp
	sub	eax, DWORD PTR _dwGetTick$[ebp]
	mov	DWORD PTR _dwGetTick$[ebp], eax

; 259  :         dwMsecQP=GetMsecSincePerfCounter(li_qp,TRUE);

	push	1
	mov	edx, DWORD PTR _li_qp$[ebp+4]
	push	edx
	mov	eax, DWORD PTR _li_qp$[ebp]
	push	eax
	call	_GetMsecSincePerfCounter
	add	esp, 12					; 0000000cH
	mov	DWORD PTR _dwMsecQP$[ebp], eax

; 260  :         dwResRdtsc=GetResRdtsc(li_rdtsc,TRUE);

	push	1
	mov	ecx, DWORD PTR _li_rdtsc$[ebp+4]
	push	ecx
	mov	edx, DWORD PTR _li_rdtsc$[ebp]
	push	edx
	call	_GetResRdtsc
	add	esp, 12					; 0000000cH
	mov	DWORD PTR _dwResRdtsc$[ebp], eax
	mov	DWORD PTR _dwResRdtsc$[ebp+4], edx

; 261  :         printf("total uncompress size = %u, in %u step\n",lSizeUncpr,step);

	mov	eax, DWORD PTR _step$2[ebp]
	push	eax
	mov	ecx, DWORD PTR _lSizeUncpr$[ebp]
	push	ecx
	push	OFFSET $SG96980
	call	_printf
	add	esp, 12					; 0000000cH

; 262  :         printf("time = %u msec = %f sec\n",dwGetTick,dwGetTick/(double)1000.);

	mov	edx, DWORD PTR _dwGetTick$[ebp]
	mov	DWORD PTR tv443[ebp], edx
	cvtsi2sd xmm0, DWORD PTR tv443[ebp]
	mov	eax, DWORD PTR tv443[ebp]
	shr	eax, 31					; 0000001fH
	addsd	xmm0, QWORD PTR __xmm@41f00000000000000000000000000000[eax*8]
	divsd	xmm0, QWORD PTR __real@408f400000000000
	sub	esp, 8
	movsd	QWORD PTR [esp], xmm0
	mov	ecx, DWORD PTR _dwGetTick$[ebp]
	push	ecx
	push	OFFSET $SG96981
	call	_printf
	add	esp, 16					; 00000010H

; 263  :         printf("uncpr  time QP = %u msec = %f sec\n",dwMsecQP,dwMsecQP/(double)1000.);

	mov	edx, DWORD PTR _dwMsecQP$[ebp]
	mov	DWORD PTR tv450[ebp], edx
	cvtsi2sd xmm0, DWORD PTR tv450[ebp]
	mov	eax, DWORD PTR tv450[ebp]
	shr	eax, 31					; 0000001fH
	addsd	xmm0, QWORD PTR __xmm@41f00000000000000000000000000000[eax*8]
	divsd	xmm0, QWORD PTR __real@408f400000000000
	sub	esp, 8
	movsd	QWORD PTR [esp], xmm0
	mov	ecx, DWORD PTR _dwMsecQP$[ebp]
	push	ecx
	push	OFFSET $SG96982
	call	_printf
	add	esp, 16					; 00000010H

; 264  :         printf("uncpr  result rdtsc = %I64x\n\n",dwResRdtsc.QuadPart);

	mov	edx, DWORD PTR _dwResRdtsc$[ebp+4]
	push	edx
	mov	eax, DWORD PTR _dwResRdtsc$[ebp]
	push	eax
	push	OFFSET $SG96983
	call	_printf
	add	esp, 12					; 0000000cH

; 265  :     }
; 266  : 
; 267  :     if (lSizeUncpr==lFileSize)

	mov	ecx, DWORD PTR _lSizeUncpr$[ebp]
	cmp	ecx, DWORD PTR _lFileSize$[ebp]
	jne	SHORT $LN15@main

; 268  :     {
; 269  :         if (memcmp(FilePtr,UncprPtr,lFileSize)==0)

	mov	edx, DWORD PTR _lFileSize$[ebp]
	push	edx
	mov	eax, DWORD PTR _UncprPtr$[ebp]
	push	eax
	mov	ecx, DWORD PTR _FilePtr$[ebp]
	push	ecx
	call	_memcmp
	add	esp, 12					; 0000000cH
	test	eax, eax
	jne	SHORT $LN15@main

; 270  :             printf("compare ok\n");

	push	OFFSET $SG96986
	call	_printf
	add	esp, 4
$LN15@main:

; 271  : 
; 272  :     }
; 273  : 
; 274  :     return 0;

	xor	eax, eax
$LN1@main:

; 275  : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN31@main
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	add	esp, 316				; 0000013cH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	3
$LN31@main:
	DD	7
	DD	$LN30@main
$LN30@main:
	DD	-20					; ffffffecH
	DD	4
	DD	$LN23@main
	DD	-32					; ffffffe0H
	DD	4
	DD	$LN24@main
	DD	-84					; ffffffacH
	DD	8
	DD	$LN25@main
	DD	-100					; ffffff9cH
	DD	8
	DD	$LN26@main
	DD	-116					; ffffff8cH
	DD	8
	DD	$LN27@main
	DD	-180					; ffffff4cH
	DD	56					; 00000038H
	DD	$LN28@main
	DD	-264					; fffffef8H
	DD	56					; 00000038H
	DD	$LN29@main
$LN29@main:
	DB	122					; 0000007aH
	DB	99					; 00000063H
	DB	112					; 00000070H
	DB	114					; 00000072H
	DB	0
$LN28@main:
	DB	122					; 0000007aH
	DB	99					; 00000063H
	DB	112					; 00000070H
	DB	114					; 00000072H
	DB	0
$LN27@main:
	DB	100					; 00000064H
	DB	119					; 00000077H
	DB	82					; 00000052H
	DB	101					; 00000065H
	DB	115					; 00000073H
	DB	82					; 00000052H
	DB	100					; 00000064H
	DB	116					; 00000074H
	DB	115					; 00000073H
	DB	99					; 00000063H
	DB	0
$LN26@main:
	DB	108					; 0000006cH
	DB	105					; 00000069H
	DB	95					; 0000005fH
	DB	114					; 00000072H
	DB	100					; 00000064H
	DB	116					; 00000074H
	DB	115					; 00000073H
	DB	99					; 00000063H
	DB	0
$LN25@main:
	DB	108					; 0000006cH
	DB	105					; 00000069H
	DB	95					; 0000005fH
	DB	113					; 00000071H
	DB	112					; 00000070H
	DB	0
$LN24@main:
	DB	70					; 00000046H
	DB	105					; 00000069H
	DB	108					; 0000006cH
	DB	101					; 00000065H
	DB	80					; 00000050H
	DB	116					; 00000074H
	DB	114					; 00000072H
	DB	0
$LN23@main:
	DB	108					; 0000006cH
	DB	70					; 00000046H
	DB	105					; 00000069H
	DB	108					; 0000006cH
	DB	101					; 00000065H
	DB	83					; 00000053H
	DB	105					; 00000069H
	DB	122					; 0000007aH
	DB	101					; 00000065H
	DB	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File g:\ctp2\zlib1211\zlib-1.2.11\contrib\testzlib\testzlib.c
_TEXT	SEGMENT
_retVal$ = -12						; size = 4
_ptr$ = -8						; size = 4
_stream$ = -4						; size = 4
_filename$ = 8						; size = 4
_plFileSize$ = 12					; size = 4
_pFilePtr$ = 16						; size = 4
_ReadFileMemory PROC

; 120  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH
	push	esi
	mov	DWORD PTR [ebp-12], -858993460		; ccccccccH
	mov	DWORD PTR [ebp-8], -858993460		; ccccccccH
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH

; 121  :     FILE* stream;
; 122  :     unsigned char* ptr;
; 123  :     int retVal=1;

	mov	DWORD PTR _retVal$[ebp], 1

; 124  :     stream=fopen(filename, "rb");

	mov	esi, esp
	push	OFFSET $SG96905
	mov	eax, DWORD PTR _filename$[ebp]
	push	eax
	call	DWORD PTR __imp__fopen
	add	esp, 8
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _stream$[ebp], eax

; 125  :     if (stream==NULL)

	cmp	DWORD PTR _stream$[ebp], 0
	jne	SHORT $LN2@ReadFileMe

; 126  :         return 0;

	xor	eax, eax
	jmp	$LN1@ReadFileMe
$LN2@ReadFileMe:

; 127  : 
; 128  :     fseek(stream,0,SEEK_END);

	mov	esi, esp
	push	2
	push	0
	mov	ecx, DWORD PTR _stream$[ebp]
	push	ecx
	call	DWORD PTR __imp__fseek
	add	esp, 12					; 0000000cH
	cmp	esi, esp
	call	__RTC_CheckEsp

; 129  : 
; 130  :     *plFileSize=ftell(stream);

	mov	esi, esp
	mov	edx, DWORD PTR _stream$[ebp]
	push	edx
	call	DWORD PTR __imp__ftell
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	ecx, DWORD PTR _plFileSize$[ebp]
	mov	DWORD PTR [ecx], eax

; 131  :     fseek(stream,0,SEEK_SET);

	mov	esi, esp
	push	0
	push	0
	mov	edx, DWORD PTR _stream$[ebp]
	push	edx
	call	DWORD PTR __imp__fseek
	add	esp, 12					; 0000000cH
	cmp	esi, esp
	call	__RTC_CheckEsp

; 132  :     ptr=malloc((*plFileSize)+1);

	mov	eax, DWORD PTR _plFileSize$[ebp]
	mov	ecx, DWORD PTR [eax]
	add	ecx, 1
	mov	esi, esp
	push	ecx
	call	DWORD PTR __imp__malloc
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _ptr$[ebp], eax

; 133  :     if (ptr==NULL)

	cmp	DWORD PTR _ptr$[ebp], 0
	jne	SHORT $LN3@ReadFileMe

; 134  :         retVal=0;

	mov	DWORD PTR _retVal$[ebp], 0
	jmp	SHORT $LN4@ReadFileMe
$LN3@ReadFileMe:

; 135  :     else
; 136  :     {
; 137  :         if (fread(ptr, 1, *plFileSize,stream) != (*plFileSize))

	mov	esi, esp
	mov	edx, DWORD PTR _stream$[ebp]
	push	edx
	mov	eax, DWORD PTR _plFileSize$[ebp]
	mov	ecx, DWORD PTR [eax]
	push	ecx
	push	1
	mov	edx, DWORD PTR _ptr$[ebp]
	push	edx
	call	DWORD PTR __imp__fread
	add	esp, 16					; 00000010H
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	ecx, DWORD PTR _plFileSize$[ebp]
	cmp	eax, DWORD PTR [ecx]
	je	SHORT $LN4@ReadFileMe

; 138  :             retVal=0;

	mov	DWORD PTR _retVal$[ebp], 0
$LN4@ReadFileMe:

; 139  :     }
; 140  :     fclose(stream);

	mov	esi, esp
	mov	edx, DWORD PTR _stream$[ebp]
	push	edx
	call	DWORD PTR __imp__fclose
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp

; 141  :     *pFilePtr=ptr;

	mov	eax, DWORD PTR _pFilePtr$[ebp]
	mov	ecx, DWORD PTR _ptr$[ebp]
	mov	DWORD PTR [eax], ecx

; 142  :     return retVal;

	mov	eax, DWORD PTR _retVal$[ebp]
$LN1@ReadFileMe:

; 143  : }

	pop	esi
	add	esp, 12					; 0000000cH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_ReadFileMemory ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File g:\ctp2\zlib1211\zlib-1.2.11\contrib\testzlib\testzlib.c
_TEXT	SEGMENT
_dwRet$ = -72						; size = 4
_dwLog$ = -68						; size = 4
_tickSecShifted$ = -64					; size = 8
_ticksShifted$ = -56					; size = 8
_ticks$ = -44						; size = 8
_ticksPerSecond$ = -28					; size = 8
_endTime64$ = -12					; size = 8
_beginTime64$ = 8					; size = 8
_fComputeTimeQueryPerf$ = 16				; size = 4
_GetMsecSincePerfCounter PROC

; 94   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 72					; 00000048H
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-72]
	mov	ecx, 18					; 00000012H
	mov	eax, -858993460				; ccccccccH
	rep stosd

; 95   :     LARGE_INTEGER endTime64,ticksPerSecond,ticks;
; 96   :     DWORDLONG ticksShifted,tickSecShifted;
; 97   :     DWORD dwLog=16+0;

	mov	DWORD PTR _dwLog$[ebp], 16		; 00000010H

; 98   :     DWORD dwRet;
; 99   :     if ((!fComputeTimeQueryPerf) || (!QueryPerformanceCounter(&endTime64)))

	cmp	DWORD PTR _fComputeTimeQueryPerf$[ebp], 0
	je	SHORT $LN4@GetMsecSin
	mov	esi, esp
	lea	eax, DWORD PTR _endTime64$[ebp]
	push	eax
	call	DWORD PTR __imp__QueryPerformanceCounter@4
	cmp	esi, esp
	call	__RTC_CheckEsp
	test	eax, eax
	jne	SHORT $LN2@GetMsecSin
$LN4@GetMsecSin:

; 100  :         dwRet = (GetTickCount() - beginTime64.LowPart)*1;

	mov	esi, esp
	call	DWORD PTR __imp__GetTickCount@0
	cmp	esi, esp
	call	__RTC_CheckEsp
	sub	eax, DWORD PTR _beginTime64$[ebp]
	mov	DWORD PTR _dwRet$[ebp], eax
	jmp	SHORT $LN3@GetMsecSin
$LN2@GetMsecSin:

; 101  :     else
; 102  :     {
; 103  :         MyDoMinus64(&ticks,endTime64,beginTime64);

	mov	ecx, DWORD PTR _beginTime64$[ebp+4]
	push	ecx
	mov	edx, DWORD PTR _beginTime64$[ebp]
	push	edx
	mov	eax, DWORD PTR _endTime64$[ebp+4]
	push	eax
	mov	ecx, DWORD PTR _endTime64$[ebp]
	push	ecx
	lea	edx, DWORD PTR _ticks$[ebp]
	push	edx
	call	_MyDoMinus64
	add	esp, 20					; 00000014H

; 104  :         QueryPerformanceFrequency(&ticksPerSecond);

	mov	esi, esp
	lea	eax, DWORD PTR _ticksPerSecond$[ebp]
	push	eax
	call	DWORD PTR __imp__QueryPerformanceFrequency@4
	cmp	esi, esp
	call	__RTC_CheckEsp

; 105  : 
; 106  : 
; 107  :         {
; 108  :             ticksShifted = Int64ShrlMod32(*(DWORDLONG*)&ticks,dwLog);

	mov	ecx, DWORD PTR _dwLog$[ebp]
	push	ecx
	mov	edx, DWORD PTR _ticks$[ebp+4]
	push	edx
	mov	eax, DWORD PTR _ticks$[ebp]
	push	eax
	call	_Int64ShrlMod32@12
	mov	DWORD PTR _ticksShifted$[ebp], eax
	mov	DWORD PTR _ticksShifted$[ebp+4], edx

; 109  :             tickSecShifted = Int64ShrlMod32(*(DWORDLONG*)&ticksPerSecond,dwLog);

	mov	ecx, DWORD PTR _dwLog$[ebp]
	push	ecx
	mov	edx, DWORD PTR _ticksPerSecond$[ebp+4]
	push	edx
	mov	eax, DWORD PTR _ticksPerSecond$[ebp]
	push	eax
	call	_Int64ShrlMod32@12
	mov	DWORD PTR _tickSecShifted$[ebp], eax
	mov	DWORD PTR _tickSecShifted$[ebp+4], edx

; 110  : 
; 111  :         }
; 112  : 
; 113  :         dwRet = (DWORD)((((DWORD)ticksShifted)*1000)/(DWORD)(tickSecShifted));

	imul	eax, DWORD PTR _ticksShifted$[ebp], 1000
	xor	edx, edx
	div	DWORD PTR _tickSecShifted$[ebp]
	mov	DWORD PTR _dwRet$[ebp], eax

; 114  :         dwRet *=1;

	mov	ecx, DWORD PTR _dwRet$[ebp]
	mov	DWORD PTR _dwRet$[ebp], ecx
$LN3@GetMsecSin:

; 115  :     }
; 116  :     return dwRet;

	mov	eax, DWORD PTR _dwRet$[ebp]

; 117  : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN10@GetMsecSin
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	add	esp, 72					; 00000048H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
$LN10@GetMsecSin:
	DD	3
	DD	$LN9@GetMsecSin
$LN9@GetMsecSin:
	DD	-12					; fffffff4H
	DD	8
	DD	$LN6@GetMsecSin
	DD	-28					; ffffffe4H
	DD	8
	DD	$LN7@GetMsecSin
	DD	-44					; ffffffd4H
	DD	8
	DD	$LN8@GetMsecSin
$LN8@GetMsecSin:
	DB	116					; 00000074H
	DB	105					; 00000069H
	DB	99					; 00000063H
	DB	107					; 0000006bH
	DB	115					; 00000073H
	DB	0
$LN7@GetMsecSin:
	DB	116					; 00000074H
	DB	105					; 00000069H
	DB	99					; 00000063H
	DB	107					; 0000006bH
	DB	115					; 00000073H
	DB	80					; 00000050H
	DB	101					; 00000065H
	DB	114					; 00000072H
	DB	83					; 00000053H
	DB	101					; 00000065H
	DB	99					; 00000063H
	DB	111					; 0000006fH
	DB	110					; 0000006eH
	DB	100					; 00000064H
	DB	0
$LN6@GetMsecSin:
	DB	101					; 00000065H
	DB	110					; 0000006eH
	DB	100					; 00000064H
	DB	84					; 00000054H
	DB	105					; 00000069H
	DB	109					; 0000006dH
	DB	101					; 00000065H
	DB	54					; 00000036H
	DB	52					; 00000034H
	DB	0
_GetMsecSincePerfCounter ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File g:\ctp2\zlib1211\zlib-1.2.11\contrib\testzlib\testzlib.c
_TEXT	SEGMENT
_pbeginTime64$ = 8					; size = 4
_fComputeTimeQueryPerf$ = 12				; size = 4
_BeginCountPerfCounter PROC

; 85   : {

	push	ebp
	mov	ebp, esp
	push	esi

; 86   :     if ((!fComputeTimeQueryPerf) || (!QueryPerformanceCounter(pbeginTime64)))

	cmp	DWORD PTR _fComputeTimeQueryPerf$[ebp], 0
	je	SHORT $LN3@BeginCount
	mov	esi, esp
	mov	eax, DWORD PTR _pbeginTime64$[ebp]
	push	eax
	call	DWORD PTR __imp__QueryPerformanceCounter@4
	cmp	esi, esp
	call	__RTC_CheckEsp
	test	eax, eax
	jne	SHORT $LN1@BeginCount
$LN3@BeginCount:

; 87   :     {
; 88   :         pbeginTime64->LowPart = GetTickCount();

	mov	esi, esp
	call	DWORD PTR __imp__GetTickCount@0
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	ecx, DWORD PTR _pbeginTime64$[ebp]
	mov	DWORD PTR [ecx], eax

; 89   :         pbeginTime64->HighPart = 0;

	mov	edx, DWORD PTR _pbeginTime64$[ebp]
	mov	DWORD PTR [edx+4], 0
$LN1@BeginCount:

; 90   :     }
; 91   : }

	pop	esi
	cmp	ebp, esp
	call	__RTC_CheckEsp
	pop	ebp
	ret	0
_BeginCountPerfCounter ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File g:\ctp2\zlib1211\zlib-1.2.11\contrib\testzlib\testzlib.c
_TEXT	SEGMENT
_endTime64$ = -28					; size = 8
_LIres$ = -12						; size = 8
_beginTime64$ = 8					; size = 8
_fComputeTimeQueryPerf$ = 16				; size = 4
_GetResRdtsc PROC

; 58   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 32					; 00000020H
	mov	eax, -858993460				; ccccccccH
	mov	DWORD PTR [ebp-32], eax
	mov	DWORD PTR [ebp-28], eax
	mov	DWORD PTR [ebp-24], eax
	mov	DWORD PTR [ebp-20], eax
	mov	DWORD PTR [ebp-16], eax
	mov	DWORD PTR [ebp-12], eax
	mov	DWORD PTR [ebp-8], eax
	mov	DWORD PTR [ebp-4], eax

; 59   :     LARGE_INTEGER LIres,endTime64;
; 60   :     myGetRDTSC32(&endTime64);

	lea	eax, DWORD PTR _endTime64$[ebp]
	push	eax
	call	_myGetRDTSC32
	add	esp, 4

; 61   : 
; 62   :     LIres.LowPart=LIres.HighPart=0;

	mov	DWORD PTR _LIres$[ebp+4], 0
	mov	ecx, DWORD PTR _LIres$[ebp+4]
	mov	DWORD PTR _LIres$[ebp], ecx

; 63   :     MyDoMinus64(&LIres,endTime64,beginTime64);

	mov	edx, DWORD PTR _beginTime64$[ebp+4]
	push	edx
	mov	eax, DWORD PTR _beginTime64$[ebp]
	push	eax
	mov	ecx, DWORD PTR _endTime64$[ebp+4]
	push	ecx
	mov	edx, DWORD PTR _endTime64$[ebp]
	push	edx
	lea	eax, DWORD PTR _LIres$[ebp]
	push	eax
	call	_MyDoMinus64
	add	esp, 20					; 00000014H

; 64   :     return LIres;

	mov	eax, DWORD PTR _LIres$[ebp]
	mov	edx, DWORD PTR _LIres$[ebp+4]

; 65   : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN6@GetResRdts
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	add	esp, 32					; 00000020H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	3
$LN6@GetResRdts:
	DD	2
	DD	$LN5@GetResRdts
$LN5@GetResRdts:
	DD	-12					; fffffff4H
	DD	8
	DD	$LN3@GetResRdts
	DD	-28					; ffffffe4H
	DD	8
	DD	$LN4@GetResRdts
$LN4@GetResRdts:
	DB	101					; 00000065H
	DB	110					; 0000006eH
	DB	100					; 00000064H
	DB	84					; 00000054H
	DB	105					; 00000069H
	DB	109					; 0000006dH
	DB	101					; 00000065H
	DB	54					; 00000036H
	DB	52					; 00000034H
	DB	0
$LN3@GetResRdts:
	DB	76					; 0000004cH
	DB	73					; 00000049H
	DB	114					; 00000072H
	DB	101					; 00000065H
	DB	115					; 00000073H
	DB	0
_GetResRdtsc ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File g:\ctp2\zlib1211\zlib-1.2.11\contrib\testzlib\testzlib.c
_TEXT	SEGMENT
_pbeginTime64$ = 8					; size = 4
_BeginCountRdtsc PROC

; 53   : {

	push	ebp
	mov	ebp, esp

; 54   :     myGetRDTSC32(pbeginTime64);

	mov	eax, DWORD PTR _pbeginTime64$[ebp]
	push	eax
	call	_myGetRDTSC32
	add	esp, 4

; 55   : }

	cmp	ebp, esp
	call	__RTC_CheckEsp
	pop	ebp
	ret	0
_BeginCountRdtsc ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File g:\ctp2\zlib1211\zlib-1.2.11\contrib\testzlib\testzlib.c
_TEXT	SEGMENT
_dwEax$ = -8						; size = 4
_dwEdx$ = -4						; size = 4
_pbeginTime64$ = 8					; size = 4
_myGetRDTSC32 PROC

; 40   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 8
	mov	DWORD PTR [ebp-8], -858993460		; ccccccccH
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH

; 41   :     DWORD dwEdx,dwEax;
; 42   :     _asm
; 43   :     {
; 44   :         rdtsc

	rdtsc

; 45   :         mov dwEax,eax

	mov	DWORD PTR _dwEax$[ebp], eax

; 46   :         mov dwEdx,edx

	mov	DWORD PTR _dwEdx$[ebp], edx

; 47   :     }
; 48   :     pbeginTime64->LowPart=dwEax;

	mov	eax, DWORD PTR _pbeginTime64$[ebp]
	mov	ecx, DWORD PTR _dwEax$[ebp]
	mov	DWORD PTR [eax], ecx

; 49   :     pbeginTime64->HighPart=dwEdx;

	mov	edx, DWORD PTR _pbeginTime64$[ebp]
	mov	eax, DWORD PTR _dwEdx$[ebp]
	mov	DWORD PTR [edx+4], eax

; 50   : }

	add	esp, 8
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_myGetRDTSC32 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File g:\ctp2\zlib1211\zlib-1.2.11\contrib\testzlib\testzlib.c
_TEXT	SEGMENT
_R$ = 8							; size = 4
_A$ = 12						; size = 8
_B$ = 20						; size = 8
_MyDoMinus64 PROC

; 9    : {

	push	ebp
	mov	ebp, esp

; 10   :     R->HighPart = A.HighPart - B.HighPart;

	mov	eax, DWORD PTR _A$[ebp+4]
	sub	eax, DWORD PTR _B$[ebp+4]
	mov	ecx, DWORD PTR _R$[ebp]
	mov	DWORD PTR [ecx+4], eax

; 11   :     if (A.LowPart >= B.LowPart)

	mov	edx, DWORD PTR _A$[ebp]
	cmp	edx, DWORD PTR _B$[ebp]
	jb	SHORT $LN2@MyDoMinus6

; 12   :         R->LowPart = A.LowPart - B.LowPart;

	mov	eax, DWORD PTR _A$[ebp]
	sub	eax, DWORD PTR _B$[ebp]
	mov	ecx, DWORD PTR _R$[ebp]
	mov	DWORD PTR [ecx], eax
	jmp	SHORT $LN1@MyDoMinus6
$LN2@MyDoMinus6:

; 13   :     else
; 14   :     {
; 15   :         R->LowPart = A.LowPart - B.LowPart;

	mov	edx, DWORD PTR _A$[ebp]
	sub	edx, DWORD PTR _B$[ebp]
	mov	eax, DWORD PTR _R$[ebp]
	mov	DWORD PTR [eax], edx

; 16   :         R->HighPart --;

	mov	ecx, DWORD PTR _R$[ebp]
	mov	edx, DWORD PTR [ecx+4]
	sub	edx, 1
	mov	eax, DWORD PTR _R$[ebp]
	mov	DWORD PTR [eax+4], edx
$LN1@MyDoMinus6:

; 17   :     }
; 18   : }

	pop	ebp
	ret	0
_MyDoMinus64 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File c:\program files (x86)\windows kits\10\include\10.0.19041.0\um\winnt.h
;	COMDAT _Int64ShrlMod32@12
_TEXT	SEGMENT
_Value$ = 8						; size = 8
_ShiftCount$ = 16					; size = 4
_Int64ShrlMod32@12 PROC					; COMDAT

; 1017 : {

	push	ebp
	mov	ebp, esp

; 1018 :     __asm    {
; 1019 :         mov     ecx, ShiftCount

	mov	ecx, DWORD PTR _ShiftCount$[ebp]

; 1020 :         mov     eax, dword ptr [Value]

	mov	eax, DWORD PTR _Value$[ebp]

; 1021 :         mov     edx, dword ptr [Value+4]

	mov	edx, DWORD PTR _Value$[ebp+4]

; 1022 :         shrd    eax, edx, cl

	shrd	eax, edx, cl

; 1023 :         shr     edx, cl

	shr	edx, cl

; 1024 :     }
; 1025 : }

	cmp	ebp, esp
	call	__RTC_CheckEsp
	pop	ebp
	ret	12					; 0000000cH
_Int64ShrlMod32@12 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File c:\program files (x86)\windows kits\10\include\10.0.19041.0\ucrt\stdio.h
;	COMDAT _printf
_TEXT	SEGMENT
__ArgList$ = -8						; size = 4
__Result$ = -4						; size = 4
__Format$ = 8						; size = 4
_printf	PROC						; COMDAT

; 956  :     {

	push	ebp
	mov	ebp, esp
	sub	esp, 8
	push	esi
	mov	DWORD PTR [ebp-8], -858993460		; ccccccccH
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH

; 957  :         int _Result;
; 958  :         va_list _ArgList;
; 959  :         __crt_va_start(_ArgList, _Format);

	lea	eax, DWORD PTR __Format$[ebp+4]
	mov	DWORD PTR __ArgList$[ebp], eax

; 960  :         _Result = _vfprintf_l(stdout, _Format, NULL, _ArgList);

	mov	ecx, DWORD PTR __ArgList$[ebp]
	push	ecx
	push	0
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	mov	esi, esp
	push	1
	call	DWORD PTR __imp____acrt_iob_func
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
	push	eax
	call	__vfprintf_l
	add	esp, 16					; 00000010H
	mov	DWORD PTR __Result$[ebp], eax

; 961  :         __crt_va_end(_ArgList);

	mov	DWORD PTR __ArgList$[ebp], 0

; 962  :         return _Result;

	mov	eax, DWORD PTR __Result$[ebp]

; 963  :     }

	pop	esi
	add	esp, 8
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_printf	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File c:\program files (x86)\windows kits\10\include\10.0.19041.0\ucrt\stdio.h
;	COMDAT __vfprintf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfprintf_l PROC					; COMDAT

; 644  :     {

	push	ebp
	mov	ebp, esp
	push	esi

; 645  :         return __stdio_common_vfprintf(_CRT_INTERNAL_LOCAL_PRINTF_OPTIONS, _Stream, _Format, _Locale, _ArgList);

	mov	esi, esp
	mov	eax, DWORD PTR __ArgList$[ebp]
	push	eax
	mov	ecx, DWORD PTR __Locale$[ebp]
	push	ecx
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	mov	eax, DWORD PTR __Stream$[ebp]
	push	eax
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax+4]
	push	ecx
	mov	edx, DWORD PTR [eax]
	push	edx
	call	DWORD PTR __imp____stdio_common_vfprintf
	add	esp, 24					; 00000018H
	cmp	esi, esp
	call	__RTC_CheckEsp

; 646  :     }

	pop	esi
	cmp	ebp, esp
	call	__RTC_CheckEsp
	pop	ebp
	ret	0
__vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File c:\program files (x86)\windows kits\10\include\10.0.19041.0\ucrt\corecrt_stdio_config.h
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT

; 90   :     {

	push	ebp
	mov	ebp, esp

; 91   :         static unsigned __int64 _OptionsStorage;
; 92   :         return &_OptionsStorage;

	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@9 ; `__local_stdio_printf_options'::`2'::_OptionsStorage

; 93   :     }

	pop	ebp
	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
END
