language: cpp
sudo: true
dist: bionic
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libsdl2-dev
    - libsdl2-mixer-dev
    - libsdl2-image-dev
    - libtiff-dev
    - libavcodec-dev
    - libavformat-dev
    - libswscale-dev
    - byacc
    - gcc-5
    - g++-5

compiler:
    - g++

services:
    - docker

#Build steps
before_install:
    - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
    - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++

jobs:
  include:
    - stage: build
      name: "direct build"
      script:
        - ./autogen.sh
        - CFLAGS="$CFLAGS -w -fuse-ld=gold" CXXFLAGS="$CXXFLAGS -fpermissive -w -fuse-ld=gold" ./configure --enable-silent-rules
        - make
    - stage: build
      name: "direct debug build"
      script:
        - ./autogen.sh
        - CFLAGS="$CFLAGS -w -fno-omit-frame-pointer -fuse-ld=gold" CXXFLAGS="$CXXFLAGS -fno-omit-frame-pointer -fpermissive -w -fuse-ld=gold" ./configure --enable-silent-rules --enable-debug
        - make
    - stage: build
      name: "docker build"
      script:
        - docker build --pull --target builder .
